### ISSUE TITLE
Use created not modified time for latest additions

### ISSUE THREAD

**Issue by epond** [epond/porthole#2]
The Golang file descriptor (https://golang.org/pkg/os/#FileInfo) contains modification time but not creation time, the latter being needed to discover most recently added folders. This project appears to solve the problem (https://github.com/djherbis/times) but is not compatible with Go 1.3

**Comment by djherbis** [comment]
Hey, which part makes it incompatible with Go 1.3? I might be able to help resolve the issue.

**Comment by epond** [comment]
In IntelliJ I saw the message "'times_linux.go' doesn't match to target system" and jumped to a conclusion, but maybe that's because I'm developing on a mac?

**Comment by djherbis** [comment]
In Go, the filename_os.go just means that that file will only be included when building for that OS.
Since you're on mac it should use times_darwin.go (unless you are cross-compiling).

I just tried it on my mac and it worked, though I'm noticing that some of my tests are failing on mac due to it not storing millisecond precision. I'll fix that.

Let me know if its working for you.

**Comment by djherbis** [comment]
Tests are passing on my mac now that I've accounted for the second-level precision. Released v1.01 so this is included as a bug fix release in v1.

Thanks!

**Comment by epond** [comment]
Precision is not important for this project but speed is since folder hierarchies are being [scanned for their folder creation times](https://github.com/epond/porthole/blob/1b015a9eed253a270c3d6ff9fe510541a8b731ef/folderScanner.go#L29). I don't see an equivalent for the _os.Readdir_ function so is my only option to call _times.Get(fi os.FileInfo)_ for every FileInfo?

**Comment by djherbis** [comment]
Get() should be really fast, it just does a type assertion and builds a struct:
https://github.com/djherbis/times/blob/master/times_darwin.go#L33

Doing times.Get() on all the results of readdir should be fast.

**Comment by epond** [comment]
That is very encouraging. Thank you!

**Comment by epond** [comment]
Regarding the tests for the times library, these were also failing for me on a mac but are now passing after your latest commit.

**Comment by djherbis** [comment]
Thought I'd give you a heads up. I was working on some similar additions to times to what you are working on including:
- convert []os.FileInfo into []times.FileInfo (os.FileInfo + Timespec)
- sort []times.FileInfo based on any of the times

I think you'll be able to re-use this code. I'll try and publish it tonight.

**Comment by epond** [comment]
Linux does not hold creation time for files and folders :(

**Comment by djherbis** [comment]
Yeah birthtime is not available on linux, you could always just do best-effort though.
Like, if the OS supports birthtime, use it. Otherwise use mod time.

The main reason Go doesn't expose all the times is because they aren't supported across all platforms (at the OS level), and even when they are supported, some systems have to turn them 'on'.
